PlotWait(Orders_MinDist_G,Waits_MinDist_G,Orders_MinDist_TD,Waits_MinDist_TD,Orders_MaxPrice_G,Waits_MaxPrice_G,Orders_MaxPrice_TD,Waits_MaxPrice_TD,Orders_MaxWait_G,Waits_MaxWait_G,Orders_MaxWait_TD,Waits_MaxWait_TD)

function PlotWait(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6) 
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 25-Jul-2019 19:00:23

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Greedy, Min Distance');

% Create plot
plot(X2,Y2,'DisplayName','TD, Min Distance');

% Create plot
plot(X3,Y3,'DisplayName','Greedy, Max Price');

% Create plot
plot(X4,Y4,'DisplayName','TD, Max Price');

% Create plot
plot(X5,Y5,'DisplayName','Greedy, Max Wait');

% Create plot
plot(X6,Y6,'DisplayName','TD, Max Wait');

% Create ylabel
ylabel({'Average Wait per Order'});

% Create xlabel
xlabel({'Time'});

% Create title
title({'Average Wait over Time'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1012.65822784811 78987.3417721519]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[10.0135669820652 18.0135669820652]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times new Roman');
set(axes1,'FontSize',10);
% Create legend
legend(axes1,'show');
end

